import asyncio
import httpx
import json
import logging
import sys
import os
import tempfile
from typing import Optional, Dict, Any
from mcp.server.fastmcp import FastMCP

# Configure logging to stderr (required for MCP servers as stdout is used for communication)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    stream=sys.stderr
)
logger = logging.getLogger("sand-martin")

# Initialize FastMCP server
mcp = FastMCP(
    "sand-martin",
    description="""
    Securely orchestrates the Grasshopper canvas within Rhino using the Sand Martin Host.
    
    SECURITY & AUTHENTICATION:
    This server requires a random 32-character 'shared secret' token generated by the 
    Sand Martin Host in Rhino.
    
    1. The token is stored in the system's temporary directory in a file named 'sand_martin.token'.
    2. This server automatically attempts to read that file to authenticate requests.
    3. If authentication fails, the agent should verify the 'Sand Martin Server' is running 
       in Grasshopper and check the temp file location.
    """
)

# Security: Bind to explicit loopback address
HOST_URL = "http://127.0.0.1:8081"

def _get_auth_token() -> Optional[str]:
    """
    Retrieves the auth token from environment variable or temp file.
    AI Agents: You can find this token in `os.path.join(tempfile.gettempdir(), 'sand_martin.token')`
    if it is not provided in the SAND_MARTIN_TOKEN environment variable.
    """
    # 1. Check environment variable
    token = os.environ.get("SAND_MARTIN_TOKEN")
    if token:
        return token
    
    # 2. Check temporary file for auto-discovery
    token_path = os.path.join(tempfile.gettempdir(), "sand_martin.token")
    if os.path.exists(token_path):
        try:
            with open(token_path, "r") as f:
                return f.read().strip()
        except Exception as e:
            logger.warning(f"Failed to read token file: {e}")
            
    return None

async def _make_request(method: str, endpoint: str, data: Optional[Dict[str, Any]] = None) -> str:
    """Helper to make requests to the Sand Martin C# Host."""
    
    async def _execute_request(current_token: str):
        headers = {
            "Authorization": f"Bearer {current_token}",
            "Content-Type": "application/json"
        }
        async with httpx.AsyncClient(timeout=30.0) as client:
            url = f"{HOST_URL}{endpoint}"
            if method == "GET":
                return await client.get(url, headers=headers)
            elif method == "POST":
                return await client.post(url, json=data, headers=headers)
            elif method == "PATCH":
                return await client.patch(url, json=data, headers=headers)
            elif method == "DELETE":
                return await client.delete(url, headers=headers)
            else:
                raise ValueError(f"Unsupported method: {method}")

    # 1. Hot Discovery: Always get the latest token from disk/env
    token = _get_auth_token()
    if not token:
        msg = (
            "Authentication Error: SAND_MARTIN_TOKEN environment variable is not set and "
            "the discovery file 'sand_martin.token' was not found in the system temp directory. "
            "Please ensure the Sand Martin Server is running in Grasshopper."
        )
        logger.error(msg)
        return json.dumps({"status": "error", "message": msg})

    logger.info(f"Making {method} request to {endpoint}")
    
    try:
        # 2. Try the request
        response = await _execute_request(token)
        
        # 3. If unauthorized (401), the token might have changed (Rhino restarted).
        # Refresh and retry ONCE.
        if response.status_code == 401:
            logger.warning("Unauthorized (401). Token may have changed. Refreshing...")
            new_token = _get_auth_token()
            if new_token and new_token != token:
                logger.info("Found new token. Retrying request...")
                response = await _execute_request(new_token)
            else:
                logger.error("Token refresh failed or token remains invalid.")

        logger.info(f"Received response: {response.status_code}")
        response.raise_for_status()
        return response.text
        
    except httpx.HTTPError as e:
        msg = f"HTTP error occurred: {str(e)}"
        logger.error(msg)
        return json.dumps({"status": "error", "message": msg})
    except Exception as e:
        msg = f"An error occurred: {str(e)}"
        logger.error(msg)
        return json.dumps({"status": "error", "message": msg})

@mcp.tool()
async def get_canvas_state() -> str:
    """Returns the current state of the Grasshopper canvas, including all nodes and their parameters."""
    logger.info("Tool called: get_canvas_state")
    return await _make_request("GET", "/state")

@mcp.tool()
async def create_node(
    type: str, 
    name: str, 
    canvas_x: int, 
    canvas_y: int, 
    parameters: Optional[Dict[str, Any]] = None
) -> str:
    """
    Creates a new node (component) on the Grasshopper canvas.
    
    Args:
        type: The type of component to create (e.g., 'Circle', 'Panel', 'CSharpComponent').
        name: The name/nickname for the new node.
        canvas_x: The X coordinate on the canvas.
        canvas_y: The Y coordinate on the canvas.
        parameters: Optional dictionary of parameters to set (e.g., {'Code': '...'} for CSharpComponent).
    """
    logger.info(f"Tool called: create_node (type={type}, name={name})")
    data = {
        "type": type,
        "name": name,
        "canvasX": canvas_x,
        "canvasY": canvas_y,
        "parameters": parameters or {}
    }
    return await _make_request("POST", "/create", data)

@mcp.tool()
async def update_node(
    node_id: str,
    name: Optional[str] = None,
    canvas_x: Optional[int] = None,
    canvas_y: Optional[int] = None,
    parameters: Optional[Dict[str, Any]] = None
) -> str:
    """
    Updates an existing node on the Grasshopper canvas.
    
    Args:
        node_id: The unique ID (GUID) of the node to update.
        name: Optional new name/nickname.
        canvas_x: Optional new X coordinate.
        canvas_y: Optional new Y coordinate.
        parameters: Optional dictionary of parameters to update.
    """
    logger.info(f"Tool called: update_node (node_id={node_id})")
    data = {}
    if name is not None: data["name"] = name
    if canvas_x is not None: data["canvasX"] = canvas_x
    if canvas_y is not None: data["canvasY"] = canvas_y
    if parameters is not None: data["parameters"] = parameters
    
    return await _make_request("PATCH", f"/update/{node_id}", data)

@mcp.tool()
async def delete_node(node_id: str) -> str:
    """
    Deletes a node from the Grasshopper canvas.
    
    Args:
        node_id: The unique ID (GUID) of the node to delete.
    """
    logger.info(f"Tool called: delete_node (node_id={node_id})")
    return await _make_request("DELETE", f"/node/{node_id}")

@mcp.tool()
async def connect_nodes(
    source_id: str,
    target_id: str,
    source_output_index: int = 0,
    target_input_index: int = 0
) -> str:
    """
    Creates a connection (wire) between two nodes on the Grasshopper canvas.
    
    Args:
        source_id: The ID of the node providing the output.
        target_id: The ID of the node receiving the input.
        source_output_index: The index of the output parameter on the source node (default 0).
        target_input_index: The index of the input parameter on the target node (default 0).
    """
    logger.info(f"Tool called: connect_nodes (from={source_id}, to={target_id})")
    data = {
        "source_id": source_id,
        "source_output_index": source_output_index,
        "target_id": target_id,
        "target_input_index": target_input_index
    }
    return await _make_request("POST", "/connection", data)

@mcp.tool()
async def disconnect_nodes(source_id: str, target_id: str) -> str:
    """
    Removes all connections between two specific nodes on the Grasshopper canvas.
    
    Args:
        source_id: The ID of the source node.
        target_id: The ID of the target node.
    """
    logger.info(f"Tool called: disconnect_nodes (from={source_id}, to={target_id})")
    data = {
        "source_id": source_id,
        "target_id": target_id
    }
    return await _make_request("POST", "/disconnect", data)

def main():
    """Entry point for the sand-martin MCP server."""
    mcp.run()

if __name__ == "__main__":
    main()
