import asyncio
import httpx
import json
import logging
import sys
import os
import tempfile
from typing import Optional, Dict, Any
from mcp.server.fastmcp import FastMCP

# Configure logging to stderr (required for MCP servers as stdout is used for communication)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    stream=sys.stderr
)
logger = logging.getLogger("sand-martin")

# Initialize FastMCP server
mcp = FastMCP(
    "sand-martin",
    instructions="""
    Securely orchestrates the Grasshopper canvas within Rhino using the Sand Martin Host.

    SECURITY & AUTHENTICATION:
    This server requires a random 32-character 'shared secret' token generated by the
    Sand Martin Host in Rhino.

    The authentication uses the 'Bearer' token format in the HTTP Authorization header:
    `Authorization: Bearer <YOUR_TOKEN>`

    Example manual verification:
    `curl -X GET http://127.0.0.1:8081/state -H "Authorization: Bearer <YOUR_TOKEN>"`

    1. If the user has not provided a token, the agent MUST first ask the user to
       copy the token from the Rhino Command History (look for 'SAND MARTIN SECURITY TOKEN').
    2. Once received, the agent should write the token to the system's temporary
       directory in a file named 'sand_martin.token' for the server to discover.
    3. If a request returns an Authentication Error or 401 Unauthorized, ask the user
       to provide the latest token from Rhino and update the file.

    WORKFLOW EXAMPLE:
    To update a slider to a specific value:
    1. Call `get_canvas_state()` to find the slider's ID.
    2. Call `get_node_details(node_id)` to see its current properties.
    3. Identify a writable property (where `"r": false`) such as 'TickValue'.
    4. Call `update_node(node_id, parameters={'TickValue': 500})` to make the change.
    """
)

# Security: Bind to explicit loopback address
HOST_URL = "http://127.0.0.1:8081"

def _get_auth_token() -> Optional[str]:
    """
    Retrieves the auth token from environment variable or temp file.
    AI Agents: You can find this token in `os.path.join(tempfile.gettempdir(), 'sand_martin.token')`
    if it is not provided in the SAND_MARTIN_TOKEN environment variable.
    """
    # 1. Check environment variable
    token = os.environ.get("SAND_MARTIN_TOKEN")
    if token:
        return token

    # 2. Check temporary file for auto-discovery
    token_path = os.path.join(tempfile.gettempdir(), "sand_martin.token")
    if os.path.exists(token_path):
        try:
            with open(token_path, "r") as f:
                return f.read().strip()
        except Exception as e:
            logger.warning(f"Failed to read token file: {e}")

    return None

async def _make_request(method: str, endpoint: str, data: Optional[Dict[str, Any]] = None) -> str:
    """Helper to make requests to the Sand Martin C# Host."""

    async def _execute_request(current_token: str):
        headers = {
            "Authorization": f"Bearer {current_token}",
            "Content-Type": "application/json"
        }
        async with httpx.AsyncClient(timeout=30.0) as client:
            url = f"{HOST_URL}{endpoint}"
            if method == "GET":
                return await client.get(url, headers=headers)
            elif method == "POST":
                return await client.post(url, json=data, headers=headers)
            elif method == "PATCH":
                return await client.patch(url, json=data, headers=headers)
            elif method == "DELETE":
                return await client.delete(url, headers=headers)
            else:
                raise ValueError(f"Unsupported method: {method}")

    # 1. Hot Discovery: Always get the latest token from disk/env
    token = _get_auth_token()
    if not token:
        msg = (
            "Authentication Error: SAND_MARTIN_TOKEN environment variable is not set and "
            "the discovery file 'sand_martin.token' was not found in the system temp directory. "
            "Please ensure the Sand Martin Server is running in Grasshopper."
        )
        logger.error(msg)
        return json.dumps({"status": "error", "message": msg})

    logger.info(f"Making {method} request to {endpoint}")

    try:
        # 2. Try the request
        response = await _execute_request(token)

        # 3. If unauthorized (401), the token might have changed (Rhino restarted).
        # Refresh and retry ONCE.
        if response.status_code == 401:
            logger.warning("Unauthorized (401). Token may have changed. Refreshing...")
            new_token = _get_auth_token()
            if new_token and new_token != token:
                logger.info("Found new token. Retrying request...")
                response = await _execute_request(new_token)
            else:
                msg = (
                    "Authentication Error: 401 Unauthorized. The security token is invalid or has expired. "
                    "Please ask the user to provide the latest 'SAND MARTIN SECURITY TOKEN' from the Rhino "
                    "Command History and write it to the 'sand_martin.token' file in the system temp directory."
                )
                logger.error(msg)
                return json.dumps({"status": "error", "message": msg})

        logger.info(f"Received response: {response.status_code}")
        response.raise_for_status()
        return response.text

    except httpx.HTTPError as e:
        msg = f"HTTP error occurred: {str(e)}"
        logger.error(msg)
        return json.dumps({"status": "error", "message": msg})
    except Exception as e:
        msg = f"An error occurred: {str(e)}"
        logger.error(msg)
        return json.dumps({"status": "error", "message": msg})

@mcp.tool()
async def get_canvas_state() -> str:
    """Returns the current state of the Grasshopper canvas, including all nodes and their parameters."""
    logger.info("Tool called: get_canvas_state")
    return await _make_request("GET", "/state")

@mcp.tool()
async def get_node_details(node_id: str) -> str:
    """
    Returns detailed dynamic state (e.g., slider values, script code) for a specific component.

    Args:
        node_id: The unique ID (GUID) of the node to inspect.
    """
    logger.info(f"Tool called: get_node_details (node_id={node_id})")
    return await _make_request("GET", f"/node/{node_id}")

@mcp.tool()
async def create_node(
    type: str,
    name: str,
    canvas_x: int,
    canvas_y: int,
    parameters: Optional[Dict[str, Any]] = None
) -> str:
    """
    Creates a new node (component) on the Grasshopper canvas.

    Args:
        type: The type of component to create (e.g., 'Circle', 'Panel', 'CSharpComponent').
        name: The name/nickname for the new node.
        canvas_x: The X coordinate on the canvas.
        canvas_y: The Y coordinate on the canvas.
        parameters: Optional dictionary of parameters to set (e.g., {'Code': '...'} for CSharpComponent).
    """
    logger.info(f"Tool called: create_node (type={type}, name={name})")
    data = {
        "type": type,
        "name": name,
        "canvasX": canvas_x,
        "canvasY": canvas_y,
        "parameters": parameters or {}
    }
    return await _make_request("POST", "/create", data)

@mcp.tool()
async def update_node(
    node_id: str,
    name: Optional[str] = None,
    canvas_x: Optional[int] = None,
    canvas_y: Optional[int] = None,
    parameters: Optional[Dict[str, Any]] = None
) -> str:
    """
    Updates an existing node on the Grasshopper canvas.

    Args:
        node_id: The unique ID (GUID) of the node to update.
        name: Optional new name/nickname.
        canvas_x: Optional new X coordinate.
        canvas_y: Optional new Y coordinate.
        parameters: Optional dictionary of parameters to update.
    """
    logger.info(f"Tool called: update_node (node_id={node_id})")
    data = {}
    if name is not None: data["name"] = name
    if canvas_x is not None: data["canvasX"] = canvas_x
    if canvas_y is not None: data["canvasY"] = canvas_y
    if parameters is not None: data["parameters"] = parameters

    return await _make_request("PATCH", f"/update/{node_id}", data)

@mcp.tool()
async def delete_node(node_id: str) -> str:
    """
    Deletes a node from the Grasshopper canvas.

    Args:
        node_id: The unique ID (GUID) of the node to delete.
    """
    logger.info(f"Tool called: delete_node (node_id={node_id})")
    return await _make_request("DELETE", f"/node/{node_id}")

@mcp.tool()
async def connect_nodes(
    source_id: str,
    target_id: str,
    source_output_index: int = 0,
    target_input_index: int = 0
) -> str:
    """
    Creates a connection (wire) between two nodes on the Grasshopper canvas.

    Args:
        source_id: The ID of the node providing the output.
        target_id: The ID of the node receiving the input.
        source_output_index: The index of the output parameter on the source node (default 0).
        target_input_index: The index of the input parameter on the target node (default 0).
    """
    logger.info(f"Tool called: connect_nodes (from={source_id}, to={target_id})")
    data = {
        "source_id": source_id,
        "source_output_index": source_output_index,
        "target_id": target_id,
        "target_input_index": target_input_index
    }
    return await _make_request("POST", "/connection", data)

@mcp.tool()
async def disconnect_nodes(source_id: str, target_id: str) -> str:
    """
    Removes all connections between two specific nodes on the Grasshopper canvas.

    Args:
        source_id: The ID of the source node.
        target_id: The ID of the target node.
    """
    logger.info(f"Tool called: disconnect_nodes (from={source_id}, to={target_id})")
    data = {
        "source_id": source_id,
        "target_id": target_id
    }
    return await _make_request("POST", "/disconnect", data)

@mcp.tool()
async def add_description(
    semantic_clusters: Optional[str] = None
) -> str:
    """
    Adds a consolidated descriptive annotation to the Grasshopper canvas based on logical clusters.

    Args:
        semantic_clusters: Optional JSON string of clusters: [{"name": "Label", "node_ids": ["id1", "id2"]}]
    """
    logger.info("Tool called: add_description")

    try:
        # 1. Get current canvas state
        state_json = await _make_request("GET", "/state")
        state = json.loads(state_json)
        nodes = state.get("nodes", [])

        if not nodes:
            return json.dumps({"status": "success", "message": "Canvas is empty, nothing to annotate."})

        clusters = []
        if semantic_clusters:
            try:
                clusters = json.loads(semantic_clusters)
            except Exception as e:
                logger.warning(f"Failed to parse semantic_clusters: {e}")

        # 2. Cleanup old organization artifacts
        cleanup_tasks = []
        layout_nodes = []
        for node in nodes:
            if node.get("nickname") in ["Section Label", "Canvas Description"] and node.get("type") == "GH_Scribble":
                cleanup_tasks.append(_make_request("DELETE", f"/node/{node['id']}"))
            else:
                layout_nodes.append(node)

        if cleanup_tasks:
            logger.info(f"Cleaning up {len(cleanup_tasks)} old scribbles...")
            await asyncio.gather(*cleanup_tasks)

        # 3. Create a Consolidated Master Annotation
        if clusters:
            node_map = {n["id"]: n for n in nodes}
            master_text_lines = ["SCRIPT DOCUMENTATION:"]
            described_node_ids = []

            for cluster in clusters:
                c_name = cluster.get("name", "Module")
                master_text_lines.append(f"• {c_name}")

                c_node_ids = [nid for nid in cluster.get("node_ids", []) if nid in node_map]
                described_node_ids.extend(c_node_ids)

            master_text = "\n".join(master_text_lines)

            # Place one master scribble at the top-left of the canvas, above existing objects.
            placement_nodes = layout_nodes or [node_map[nid] for nid in described_node_ids]
            if placement_nodes:
                min_x = min(node.get("x", 0) for node in placement_nodes)
                min_y = min(node.get("y", 0) for node in placement_nodes)
                estimated_height = max(120, len(master_text_lines) * 32)
                margin = 40
                await _make_request("POST", "/create", {
                    "type": "Scribble",
                    "name": "Canvas Description",
                    "canvasX": int(min_x),
                    "canvasY": int(min_y - estimated_height - margin),
                    "parameters": {"Text": master_text}
                })

        return json.dumps({
            "status": "success",
            "message": "Consolidated all notes into a single master annotation."
        })

    except Exception as e:
        logger.error(f"Error annotating canvas: {e}")
        return json.dumps({"status": "error", "message": str(e)})

@mcp.prompt()
def describe_canvas() -> str:
    """
    Instructions for adding consolidated explanatory annotations to a Grasshopper script.
    """
    return """
    You are a professional Technical Writer for Grasshopper scripts. Your goal is to add a single,
    comprehensive documentation block to the canvas that explains the script's logic in plain English.

    ### ANNOTATION STRATEGY:
    1. **ANALYZE:** Call `get_canvas_state()` to map the logic. Identify the functional "tracks" or "modules".
    2. **DOCUMENT:** For each module, write a brief bullet point (1-2 sentences) explaining its role.
       - Avoid all-caps.
       - Use a professional, technical tone.
    3. **CONSOLIDATE:** Combine all these descriptions into a single "SCRIPT DOCUMENTATION" string.
    4. **PLACE:** Call `add_description(semantic_clusters=...)` passing your cluster definitions.
       - The tool will automatically consolidate your notes into one Master Scribble placed far above the script to avoid overlaps.

    *Goal: Provide a clear, non-overlapping 'Readme' directly on the Grasshopper canvas.*
    """

def main():
    """Entry point for the sand-martin MCP server."""
    mcp.run()

if __name__ == "__main__":
    main()
